import numpy as np
# import matplotlib.pyplot as plt

class maze_18x18():
    
    def __init__(self,):
        print("this is 18x18 maze")
        
        
    def maze_array():
        
        size = 18
        theta = np.array([[np.nan, 1, 1, np.nan],  # s0 
                        [np.nan, 1, 1, 1],  # s1
                        [np.nan, 1, np.nan, 1],  # s2
                        [np.nan, 1, np.nan, 1],  # s3
                        [np.nan, 1, np.nan, 1],  # s4
                        [np.nan, 1, 1, 1],  # s5
                        [np.nan, np.nan, 1, 1],  # s6
                        [np.nan, 1, 1, np.nan],  # s7
                        [np.nan, 1, 1, 1],  # s8
                        [np.nan, 1, np.nan, 1],  # s9
                        [np.nan, 1, np.nan, 1],  # s10
                        [np.nan, 1, 1, 1],  # s11
                        [np.nan, 1, np.nan, 1],  # s12
                        [np.nan, 1, np.nan, 1],  # s13
                        [np.nan, 1, np.nan, 1],  # s14
                        [np.nan, 1, np.nan, 1],  # s15
                        [np.nan, 1, 1, 1],  # s16
                        [np.nan, np.nan, 1, 1],  # s17
                        [1, np.nan, 1, np.nan],  # s18
                        [1, np.nan, 1, np.nan],  # s19
                        [np.nan, 1, 1, np.nan],  # s20
                        [np.nan, 1, np.nan, 1],  # s21
                        [np.nan, 1, np.nan, 1],  # s22
                        [1, np.nan, 1, 1], # s23
                        [1, np.nan, 1, np.nan],  # s24
                        [1, np.nan, 1, np.nan],  # s25
                        [1, np.nan, 1, np.nan],  # s26
                        [np.nan, 1, np.nan, np.nan],  # s27
                        [np.nan, 1, np.nan, 1],  # s28
                        [1, 1, np.nan, 1],  # s29
                        [np.nan, 1, 1, 1],  # s30
                        [np.nan, np.nan, 1, 1],  # s31
                        [np.nan, 1, 1, np.nan],  # s32
                        [np.nan, np.nan, 1, 1],  # s33
                        [1, np.nan, 1, np.nan],  # s34
                        [1, np.nan, 1, np.nan],  # s35
                        [1, np.nan, 1, np.nan],  # s36
                        [1, np.nan, 1, np.nan],  # s37
                        [1, 1, np.nan, np.nan],  # s38
                        [np.nan, 1, np.nan, 1],  # s39
                        [np.nan, np.nan, 1, 1],  # s40
                        [1, np.nan, 1, np.nan],  # s41
                        [1, np.nan, 1, np.nan],  # s42
                        [1, np.nan, 1, np.nan],  # s43
                        [1, 1, 1, np.nan],  # s44
                        [np.nan, 1, np.nan, 1],  # s45
                        [np.nan, 1, np.nan, 1],  # s46
                        [np.nan, 1, np.nan, 1],  # s47
                        [1, np.nan, np.nan, 1],  # s48
                        [1, 1, np.nan, np.nan],  # s49
                        [1, np.nan, np.nan, 1],  # s50
                        [1, np.nan, 1, np.nan],  # s51
                        [1, np.nan, 1, np.nan],  # s52
                        [1, np.nan, 1, np.nan],  # s53
                        [1, np.nan, 1, np.nan],  # s54
                        [1, 1, 1, np.nan],  # s55
                        [np.nan, 1, np.nan, 1],  # s56
                        [np.nan, 1, np.nan, 1],  # s57
                        [1, np.nan, 1, 1],  # s58
                        [1, np.nan, 1, np.nan],  # s59
                        [1, np.nan, 1, np.nan],  # s60
                        [1, np.nan, 1, np.nan],  # s61
                        [1, 1, 1, np.nan],  # s62
                        [np.nan, 1, np.nan, 1],  # s63
                        [np.nan, 1, np.nan, 1],  # s64
                        [np.nan, 1, np.nan, 1],  # s65
                        [np.nan, 1, np.nan, 1],  # s66
                        [np.nan, 1, np.nan, 1],  # s67
                        [np.nan, np.nan, 1, 1],  # s68
                        [1, 1, 1, np.nan],  # s69
                        [1, np.nan, 1, 1],  # s70
                        [1, np.nan, 1, np.nan],  # s71
                        [1, 1, np.nan, np.nan],  # s72
                        [1, 1, np.nan, 1],  # s73
                        [np.nan, 1, np.nan, 1],  # s74
                        [np.nan, 1, np.nan, 1],  # s75
                        [1, np.nan, 1, 1],  # s76
                        [1, np.nan, 1, np.nan],  # s77
                        [1, np.nan, 1, np.nan],  # s78
                        [1, np.nan, 1, np.nan],  # s79
                        [1, np.nan, 1, np.nan],  # s80
                        [np.nan, 1, np.nan, np.nan],  # s81
                        [np.nan, 1, np.nan, 1],  # s82
                        [np.nan, 1, np.nan, 1],  # s83
                        [np.nan, 1, 1, 1],  # s84
                        [np.nan, np.nan, 1, 1],  # s85
                        [1, np.nan, 1, np.nan],  # s86
                        [1, 1, 1, np.nan],  # s87
                        [1, np.nan, 1, 1],  # s88
                        [1, np.nan, 1, np.nan],  # s89
                        [np.nan, 1, 1, np.nan],  # s90
                        [np.nan, 1, np.nan, 1],  # s91
                        [np.nan, 1, np.nan, 1],  # s92
                        [np.nan, 1, np.nan, 1],  # s93
                        [1, np.nan, 1, 1],  # s94
                        [1, 1, 1, np.nan],  # s95
                        [1, np.nan, 1, 1],  # s96
                        [1, 1, np.nan, np.nan],  # s97
                        [1, 1, np.nan, 1],  # s98
                        [np.nan, 1, np.nan, 1],  # s99
                        [np.nan, 1, np.nan, 1],  # s100
                        [np.nan, 1, np.nan, 1],  # s101
                        [1, np.nan, np.nan, 1],  # s102
                        [1, 1, 1, np.nan],  # s103
                        [1, np.nan, 1, 1],  # s104
                        [1, np.nan, 1, np.nan],  # s105
                        [1, np.nan, 1, np.nan],  # s106
                        [1, np.nan, 1, np.nan],  # s107
                        [1, np.nan, 1, np.nan],  # s108
                        [np.nan, 1, np.nan, np.nan],  # s109
                        [np.nan, 1, 1, 1],  # s110
                        [np.nan, 1, np.nan, 1],  # s111
                        [1, 1, np.nan, 1],  # s112
                        [1, 1, np.nan, 1],  # s113
                        [1, 1, np.nan, 1],  # s114
                        [np.nan, 1, np.nan, 1],  # s115
                        [np.nan, 1, np.nan, 1],  # s116
                        [np.nan, 1, np.nan, 1],  # s117
                        [np.nan, 1, np.nan, 1],  # s118
                        [np.nan, 1, 1, 1],  # s119
                        [np.nan, 1, np.nan, 1],  # s120
                        [1, np.nan, np.nan, 1],  # s121
                        [1, np.nan, 1, np.nan],  # s122
                        [1, np.nan, 1, np.nan],  # s123
                        [1, np.nan, 1, np.nan],  # s124
                        [1, np.nan, 1, np.nan],  # s125
                        [1, 1, 1, np.nan],  # s126
                        [np.nan, 1, np.nan, 1],  # s127
                        [1, 1, np.nan, 1],  # s128
                        [np.nan, 1, np.nan, 1],  # s129
                        [np.nan, 1, np.nan, 1],  # s130
                        [np.nan, 1, np.nan, 1],  # s131
                        [np.nan, 1, np.nan, 1],  # s132
                        [np.nan, np.nan, 1, 1],  # s133
                        [np.nan, 1, 1, np.nan],  # s134
                        [np.nan, 1, np.nan, 1],  # s135
                        [np.nan, np.nan, np.nan, 1],  # s136
                        [1, 1, 1, np.nan],  # s137
                        [np.nan, 1, 1, 1],  # s138
                        [np.nan, np.nan, 1, 1],  # s139
                        [1, np.nan, 1, np.nan],  # s140
                        [1, np.nan, 1, np.nan],  # s141
                        [1, np.nan, 1, np.nan],  # s142
                        [1, np.nan, 1, np.nan],  # s143
                        [1, np.nan, 1, np.nan],  # s144
                        [np.nan, 1, 1, np.nan],  # s145
                        [np.nan, 1, np.nan, 1],  # s146
                        [np.nan, 1, np.nan, 1],  # s147
                        [np.nan, 1, np.nan, 1],  # s148
                        [np.nan, 1, np.nan, 1],  # s149
                        [np.nan, 1, np.nan, 1],  # s150
                        [1, np.nan, 1, 1],  # s151
                        [1, 1, 1, np.nan],  # s152
                        [np.nan, 1, np.nan, 1],  # s153
                        [np.nan, 1, np.nan, 1],  # s154
                        [1, 1, np.nan, 1],  # s155
                        [1, 1, np.nan, 1],  # s156
                        [1, 1, np.nan, 1],  # s157
                        [1, np.nan, np.nan, 1],  # s158
                        [1, np.nan, 1, np.nan],  # s159
                        [1, np.nan, 1, np.nan],  # s160
                        [1, np.nan, 1, np.nan],  # s161
                        [1, np.nan, 1, np.nan],  # s162
                        [1, np.nan, 1, np.nan],  # s163
                        [np.nan, 1, 1, np.nan],  # s164
                        [np.nan, 1, 1, 1],  # s165
                        [np.nan, 1, 1, 1],  # s166
                        [np.nan, 1, 1, 1],  # s167
                        [np.nan, 1, np.nan, 1],  # s168
                        [1, 1, np.nan, 1],  # s169
                        [1, np.nan, 1, 1],  # s170
                        [np.nan, np.nan, 1, np.nan],  # s171
                        [np.nan, 1, 1, np.nan],  # s172
                        [np.nan, 1, np.nan, 1],  # s173
                        [np.nan, 1, np.nan, 1],  # s174
                        [np.nan, 1, np.nan, 1],  # s175
                        [np.nan, np.nan, 1, 1],  # s176
                        [1, np.nan, 1, np.nan],  # s177
                        [1, 1, 1, np.nan],  # s178
                        [1, np.nan, 1, 1],  # s179
                        [1, np.nan, 1, np.nan],  # s180
                        [1, np.nan, 1, np.nan],  # s181
                        [1, 1, 1, np.nan],  # s182
                        [1, 1, np.nan, 1],  # s183
                        [1, np.nan, np.nan, 1],  # s184
                        [1, 1, np.nan, np.nan],  # s185
                        [np.nan, 1, np.nan, 1],  # s186
                        [np.nan, 1, np.nan, 1],  # s187
                        [1, np.nan, np.nan, 1],  # s188
                        [1, np.nan, 1, np.nan],  # s189
                        [1, np.nan, 1, np.nan],  # s190
                        [np.nan, 1, 1, np.nan],  # s191
                        [np.nan, 1, np.nan, 1],  # s192
                        [np.nan, 1, np.nan, 1],  # s193
                        [1, np.nan, 1, 1],  # s194
                        [1, np.nan, 1, np.nan],  # s195
                        [1, 1, np.nan, np.nan],  # s196
                        [1, np.nan, 1, 1],  # s197
                        [1, np.nan, 1, np.nan],  # s198
                        [1, np.nan, np.nan, np.nan],  # s199
                        [1, np.nan, 1, np.nan],  # s200
                        [np.nan, np.nan, 1, np.nan],  # s201
                        [np.nan, np.nan, 1, np.nan],  # s202
                        [np.nan, 1, 1, np.nan],  # s203
                        [np.nan, 1, np.nan, 1],  # s204
                        [np.nan, 1, np.nan, 1],  # s205
                        [np.nan, 1, np.nan, 1],  # s206
                        [1, 1, np.nan, 1],  # s207
                        [1, np.nan, 1, 1],  # s208
                        [1, np.nan, 1, np.nan],  # s209
                        [np.nan, 1, np.nan, np.nan],  # s210
                        [np.nan, np.nan, 1, 1],  # s211
                        [1, np.nan, 1, np.nan],  # s212
                        [1, 1, 1, np.nan],  # s213
                        [np.nan, 1, 1, 1],  # s214
                        [1, np.nan, np.nan, 1],  # s215
                        [1, 1, 1, np.nan],  # s216
                        [np.nan, 1, np.nan, 1],  # s217
                        [1, np.nan, np.nan, 1],  # s218
                        [1, 1, 1, np.nan],  # s219
                        [1, np.nan, 1, 1],  # s220
                        [1, np.nan, 1, np.nan],  # s221
                        [np.nan, 1, np.nan, np.nan],  # s222
                        [np.nan, 1, np.nan, 1],  # s223
                        [np.nan, 1, np.nan, 1],  # s224
                        [np.nan, 1, 1, 1],  # s225
                        [1, np.nan, np.nan, 1],  # s226
                        [1, 1, np.nan, np.nan],  # s227
                        [np.nan, 1, np.nan, 1],  # s228
                        [1, np.nan, np.nan, 1],  # s229
                        [1, 1, 1, np.nan],  # s230
                        [1, 1, np.nan, 1],  # s231
                        [1, 1, np.nan, 1],  # s232
                        [np.nan, np.nan, np.nan, 1],  # s233
                        [1, 1, 1, np.nan],  # s234
                        [np.nan, 1, 1, 1],  # s235
                        [np.nan, np.nan, 1, 1],  # s236
                        [1, np.nan, 1, np.nan],  # s237
                        [1, np.nan, 1, np.nan],  # s238
                        [1, np.nan, 1, np.nan],  # s239
                        [np.nan, 1, 1, np.nan],  # s240
                        [np.nan, 1, np.nan, 1],  # s241
                        [np.nan, 1, np.nan, 1],  # s242
                        [1, 1, np.nan, 1],  # s243
                        [np.nan, 1, np.nan, 1],  # s224
                        [np.nan, 1, np.nan, 1],  # s245
                        [np.nan, 1, np.nan, 1],  # s246
                        [np.nan, 1, np.nan, 1],  # s247
                        [1, 1, np.nan, 1],  # s248
                        [np.nan, 1, np.nan, 1],  # s249
                        [np.nan, 1, np.nan, 1],  # s250
                        [np.nan, np.nan, np.nan, 1],  # s251
                        [1, 1, np.nan, np.nan],  # s252
                        [1, np.nan, np.nan, 1],  # s253
                        [1, np.nan, 1, np.nan],  # s254
                        [1, np.nan, 1, np.nan],  # s255
                        [1, np.nan, 1, np.nan],  # s256
                        [1, np.nan, 1, np.nan],  # s257
                        [1, 1, np.nan, np.nan],  # s258
                        [np.nan, 1, np.nan, 1],  # s259
                        [np.nan, 1, 1, 1],  # s260
                        [np.nan, 1, np.nan, 1],  # s261
                        [np.nan, 1, np.nan, 1],  # s262
                        [np.nan, 1, np.nan, 1],  # s263
                        [np.nan, 1, np.nan, 1],  # s264
                        [np.nan, 1, np.nan, 1],  # s265
                        [np.nan, 1, np.nan, 1],  # s266
                        [np.nan, np.nan, 1, 1],  # s267
                        [np.nan, 1, 1, np.nan],  # s268
                        [np.nan, np.nan, 1, 1],  # s269
                        [np.nan, 1, 1, np.nan],  # s270
                        [np.nan, np.nan, 1, 1],  # s271
                        [1, np.nan, 1, np.nan],  # s272
                        [1, np.nan, 1, np.nan],  # s273
                        [1, np.nan, 1, np.nan],  # s274
                        [1, np.nan, 1, np.nan],  # s275
                        [np.nan, 1, 1, np.nan],  # s276
                        [np.nan, np.nan, 1, 1],  # s277
                        [1, np.nan, 1, np.nan],  # s278
                        [np.nan, 1, 1, np.nan],  # s279
                        [np.nan, 1, np.nan, 1],  # s280
                        [np.nan, 1, np.nan, 1],  # s281
                        [np.nan, 1, np.nan, 1],  # s282
                        [np.nan, 1, np.nan, 1],  # s283
                        [np.nan, np.nan, 1, 1],  # s284
                        [1, np.nan, 1, np.nan],  # s285
                        [1, np.nan, 1, np.nan],  # s286
                        [1, np.nan, 1, np.nan],  # s287
                        [1, np.nan, 1, np.nan],  # s288
                        [1, np.nan, np.nan, np.nan],  # s289
                        [1, 1, 1, np.nan],  # s290
                        [1, np.nan, 1, 1],  # s291
                        [1, 1, 1, np.nan],  # s292
                        [1, np.nan, 1, 1],  # s293
                        [1, np.nan, 1, np.nan],  # s294
                        [1, np.nan, np.nan, np.nan],  # s295
                        [1, np.nan, 1, np.nan],  # s296
                        [1, 1, np.nan, np.nan],  # s297
                        [np.nan, 1, np.nan, 1],  # s298
                        [np.nan, 1, np.nan, 1],  # s299
                        [np.nan, 1, np.nan, 1],  # s300
                        [np.nan, 1, np.nan, 1],  # s301
                        [1, np.nan, 1, 1],  # s302
                        [1, np.nan, 1, np.nan],  # s303
                        [1, np.nan, 1, np.nan],  # s304
                        [1, np.nan, 1, np.nan],  # s305
                        [1, 1, np.nan, np.nan],  # s306
                        [np.nan, 1, np.nan, 1],  # s307
                        [1, 1, np.nan, 1],  # s308
                        [1, 1, np.nan, 1],  # s309
                        [1, 1, np.nan, 1],  # s310
                        [1, np.nan, np.nan, 1],  # s311
                        [1, 1, np.nan, np.nan],  # s312
                        [np.nan, 1, np.nan, 1],  # s313
                        [1, 1, np.nan, 1],  # s314
                        [np.nan, 1, np.nan, 1],  # s315
                        [np.nan, 1, np.nan, 1],  # s316
                        [np.nan, 1, np.nan, 1],  # s317
                        [np.nan, 1, np.nan, 1],  # s318
                        [np.nan, 1, np.nan, 1],  # s319
                        [1, np.nan, np.nan, 1],  # s320
                        [1, 1, np.nan, np.nan],  # s321
                        [1, 1, np.nan, 1],  # s322
                        [1, np.nan, np.nan, 1], ]) # s323
        
        return size, theta

        